--- a/cddl/lib/libuutil/Makefile
+++ b/cddl/lib/libuutil/Makefile
@@ -15,6 +15,8 @@
 	uu_pname.c \
 	uu_strtoint.c
 
+LDADD= -lpthread -lrt -lbsd
+
 WARNS?=	0
 CFLAGS+= -DNATIVE_BUILD
 CFLAGS+= -I${.CURDIR}/../../../cddl/contrib/opensolaris/lib/libuutil/common
--- a/cddl/lib/libzfs/Makefile
+++ b/cddl/lib/libzfs/Makefile
@@ -8,7 +8,11 @@
 LIB=	zfs
 DPADD=	${LIBMD} ${LIBPTHREAD} ${LIBUMEM} ${LIBUTIL} ${LIBM} ${LIBNVPAIR} \
 	${LIBZFS_CORE}
-LDADD=	-lmd -lpthread -lumem -lutil -lzfs_core
+LDADD=	-lmd -lpthread -lumem -lzfs_core
+
+LDADD+= -lbsd -lm
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs_core
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
 
 SRCS=	deviceid.c \
 	fsshare.c \
--- a/cddl/lib/libzpool/Makefile
+++ b/cddl/lib/libzpool/Makefile
@@ -57,7 +57,11 @@
 CFLAGS+=	-I${.CURDIR}/../../../lib/libthr/arch/${MACHINE_CPUARCH}/include
 
 DPADD=		${LIBMD} ${LIBPTHREAD} ${LIBZ}
-LDADD=		-lmd -lpthread -lz -lumem -lnvpair -lavl
+LDADD=		-lmd -lpthread -lz -lumem -lnvpair -lbsd -lrt
+
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= ${.CURDIR}/../../../cddl/lib/libavl/libavl.a
 
 # atomic.S doesn't like profiling.
 NO_PROFILE=
--- a/cddl/sbin/zfs/Makefile
+++ b/cddl/sbin/zfs/Makefile
@@ -24,6 +24,13 @@
 
 DPADD=	${LIBGEOM} ${LIBJAIL} ${LIBNVPAIR} ${LIBUMEM} \
 	${LIBUTIL} ${LIBUUTIL} ${LIBZFS_CORE} ${LIBZFS}
-LDADD=	-lgeom -ljail -lnvpair -lumem -lutil -luutil -lzfs_core -lzfs
+LDADD=	-lgeom -ljail -lnvpair -lumem -luutil -lzfs_core -lzfs
+
+LDADD+=	-lbsd
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libuutil
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs_core
 
 .include <bsd.prog.mk>
--- a/cddl/sbin/zpool/Makefile
+++ b/cddl/sbin/zpool/Makefile
@@ -28,6 +28,14 @@
 
 DPADD=	${LIBAVL} ${LIBGEOM} ${LIBNVPAIR} \
 	${LIBUMEM} ${LIBUTIL} ${LIBUUTIL} ${LIBZFS_CORE} ${LIBZFS}
-LDADD=	-lavl -lgeom -lnvpair -lumem -lutil -luutil -lzfs_core -lzfs
+LDADD=	-lgeom -lnvpair -lumem -lutil -luutil -lzfs_core -lzfs
+
+LDADD+=	-lbsd
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libuutil
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs_core
+LDADD+= ${.CURDIR}/../../../cddl/lib/libavl/libavl.a
 
 .include <bsd.prog.mk>
--- a/cddl/usr.bin/zinject/Makefile
+++ b/cddl/usr.bin/zinject/Makefile
@@ -23,4 +23,12 @@
 	${LIBZFS_CORE} ${LIBZFS} ${LIBZPOOL}
 LDADD=	-lgeom -lm -lnvpair -lumem -luutil -lzfs_core -lzfs -lzpool
 
+LDADD+= -lbsd
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libuutil
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs_core
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzpool
+
 .include <bsd.prog.mk>
--- a/cddl/usr.bin/ztest/Makefile
+++ b/cddl/usr.bin/ztest/Makefile
@@ -20,9 +20,18 @@
 
 DPADD=	${LIBGEOM} ${LIBM} ${LIBNVPAIR} ${LIBUMEM} ${LIBZPOOL} \
 	${LIBPTHREAD} ${LIBAVL} ${LIBZFS_CORE} ${LIBZFS} ${LIBUUTIL}
-LDADD=	-lgeom -lm -lnvpair -lumem -lzpool -lpthread -lavl -lzfs_core -lzfs \
+LDADD=	-lgeom -lm -lnvpair -lumem -lzpool -lpthread -lzfs_core -lzfs \
 	-luutil
 
+LDADD+=	-lbsd -ldl -lrt
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libuutil
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzpool
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs_core
+LDADD+= ${.CURDIR}/../../../cddl/lib/libavl/libavl.a
+
 CSTD=	c99
 
 CFLAGS+= -DDEBUG=1
--- a/cddl/usr.sbin/zdb/Makefile
+++ b/cddl/usr.sbin/zdb/Makefile
@@ -27,6 +27,14 @@
 	${LIBUUTIL} ${LIBZFS_CORE} ${LIBZFS} ${LIBZPOOL}
 LDADD=	-lgeom -lm -lnvpair -lpthread -lumem -luutil -lzfs_core -lzfs -lzpool
 
+LDADD+= -lbsd
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libumem
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libuutil
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzfs_core
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libzpool
+
 CFLAGS+=	-DDEBUG=1
 #DEBUG_FLAGS+=	-g
 
--- a/cddl/lib/libzfs_core/Makefile
+++ b/cddl/lib/libzfs_core/Makefile
@@ -10,6 +10,8 @@
 DPADD=	${LIBNVPAIR}
 LDADD=	-lnvpair
 
+LDADD+= -L${.CURDIR}/../../../cddl/lib/libnvpair
+
 SRCS=	libzfs_core.c \
 	libzfs_core_compat.c
 
